### ISSUE TITLE
Signing a message with EIP-712 throw an error "The address is invalid"

### ISSUE THREAD

**Issue by bonustrack** [safe-global/safe-apps-sdk#363] opened 2022-09-06 09:48 UTC
We are currently testing to sign an EIP-712 message with a Safe, we are using the latest version of the SDKs (see: https://github.com/snapshot-labs/lock/blob/master/package.json#L11-L12) with the dev instance here https://safe-team.dev.gnosisdev.com/app but somehow when we try to trigger a new 712 message to sign we got this error: 

```Result Error: The address is invalid.```

We made a test deployment here: https://bafybeidecgkelmzrlrjl2et6jrwhn4c2vs5hsjluklphxdo2kueej43ony.on.fleek.co/#/fabien.eth/proposal/0xbe992f0a433d2dbe2e0cee579e5e1bdb625cdcb3a14357ea990c6cdc3e129991
If you login with a Safe and try to cast a vote and that proposal you should get the same error.

**Comment by mikhailxyz** [comment] 2022-09-09 14:51
We have incorrect order of `eth_signTypedData` parameters:
https://github.com/safe-global/safe-apps-sdk/blob/development/packages/safe-apps-provider/src/provider.ts#L69
We have them as `[message, address]`, but according to 
https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc
it should be `[address, message]`. We'll fix it soon

**Comment by outdoteth** [comment] 2022-09-14 10:12
@mikhailxyz could you give an ETA?

**Comment by mikhailxyz** [comment] 2022-09-16 14:21
this is fixed in the latest releases

**Comment by samuveth** [comment] 2022-09-19 11:21
@mikhailxyz we have updated the package and are now running into another error.

`Result Error: Invalid typed data` 

I've tried adding `chainId` and `verifyingContract` to `domain` like [here](https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc), but that didn't fix it.

Live deployment [here](https://snapshot-ojwymuxrz-snapshot.vercel.app/)

Example data for a vote where this error occurs:

```
domain: {
    "name": "snapshot",
    "version": "0.1.4"
}

types: {
    "Vote": [
        {
            "name": "from",
            "type": "address"
        },
        {
            "name": "space",
            "type": "string"
        },
        {
            "name": "timestamp",
            "type": "uint64"
        },
        {
            "name": "proposal",
            "type": "bytes32"
        },
        {
            "name": "choice",
            "type": "uint32"
        },
        {
            "name": "reason",
            "type": "string"
        },
        {
            "name": "app",
            "type": "string"
        }
    ]
}

message: {
    "space": "pistachiodao.eth",
    "proposal": "0x38c654c0f81b63ea1839ec3b221fad6ecba474aa0c4e8b4e8bc957f70100e753",
    "choice": 2,
    "app": "snapshot",
    "reason": "",
    "from": "0x6F727219bde56b7C35Cb26D78b6019cc3E76030e",
    "timestamp": 1663585488
}
```

**Comment by samuveth** [comment] 2022-09-19 11:23
Someone else also reported this https://github.com/safe-global/safe-react-apps/pull/519#issuecomment-1250850229

**Comment by mikhailxyz** [comment] 2022-09-19 13:22
@samuveth we'll go live soon with the fix, but unfortunately, we couldn't make it work with the snapshot. The reason for this was that you're passing an `EIP712Domain` type which is defined by the [standard](https://eips.ethereum.org/EIPS/eip-712#rationale-for-domainseparator) and most libraries include it already. The ethers.js library we use doesn't take `primaryType` as an argument and tries to figure it out by itself, and in the case of your message, it fails to do so.

**Comment by samuveth** [comment] 2022-09-20 04:16
@mikhailxyz I'm not aware that we are passing an `EIP712Domain` type anywhere. We are also using ethers.js which is working well with EIP712 on our side.

**Comment by mikhailxyz** [comment] 2022-09-20 07:58
@samuveth here is an example of what happens when you try to hash the message from snapshot: https://codesandbox.io/s/flamboyant-fermi-fc14sd?file=/src/index.ts

**Comment by bonustrack** [comment] 2022-09-21 17:56
@mikhailxyz I can confirm that we aren't passing any `EIP712Domain` type, what we do actually is this: <https://codesandbox.io/s/practical-sammet-t5ovft>, here is an example of recent vote that was cast on Snapshot with all the data: https://snapshot.mypinata.cloud/ipfs/bafkreigge7fuppm3jyt7dneav5v5dtmdgkt3rqd4xvqmnaw4otnm5lanoq

**Comment by firatkaratas** [comment] 2022-09-22 10:03
Hey all, I'm still having the same error using the web client of Gnosis Safe. I'm assuming that fix hasn't been deployed yet. Is there an ETA on the deployment of the fix?

**Comment by mikhailxyz** [comment] 2022-09-22 10:13
> Hey all, I'm still having the same error using the web client of Gnosis Safe. I'm assuming that fix hasn't been deployed yet. Is there an ETA on the deployment of the fix?

could you please share a reproducible example?

**Comment by firatkaratas** [comment] 2022-09-22 10:21
Hey @mikhailxyz,

I posted this issue a while ago: https://ethereum.stackexchange.com/questions/135312/error-while-doing-eth-signtypeddata-using-gnosis-safe-via-walletconnect

Your comment on the question was that problem would be fixed by this issue. I assumed that [this PR](https://github.com/safe-global/safe-react-apps/pull/519) is the one to deploy the fix to Gnosis Safe web app, am I wrong?

**Comment by samuveth** [comment] 2022-09-22 11:39
@mikhailxyz it seems he forgot the remove the `EIP712Domain` in the example. Without it it is working  https://codesandbox.io/s/musing-firefly-bzg4n5?file=/src/index.ts

**Comment by mikhailxyz** [comment] 2022-09-22 13:15
> @mikhailxyz it seems he forgot the remove the `EIP712Domain` in the example. Without it it is working https://codesandbox.io/s/musing-firefly-bzg4n5?file=/src/index.ts

Yes, I know it is working. The problem is that when we receive a message from the dApp it is not removed there

**Comment by firatkaratas** [comment] 2022-09-23 07:19
Now I'm getting this error while doing `signTypedData` on a web client using WalletConnect. any tips @mikhailxyz ?

<img width="528" alt="Screenshot 2022-09-23 at 09 16 50" src="https://user-images.githubusercontent.com/10280395/191909805-415db7b9-8813-4482-a071-53c0a1f6aade.png">

**Comment by mikhailxyz** [comment] 2022-09-23 10:13
@samuveth @firatkaratas I confirmed with Richard that there's a bug on our side in terms of JSON-RPC payload handling, we'll fix it next week

**Comment by mikhailxyz** [comment] 2022-10-06 14:36
@samuveth I found the problem, the problem is that your message is encoded as a string instead of JSON as in specs: https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc

It seems a lot of projects are doing that so we'll add support for that soon 🤷

**Closed** 2022-10-11 09:29 UTC

**Comment by samuveth** [comment] 2022-10-18 11:23
@mikhailxyz are these fixes live yet? I don't seem to get a new version of `safe-apps-sdk` yet

**Comment by mikhailxyz** [comment] 2022-10-18 11:55
@samuveth yes they're live

**Comment by samuveth** [comment] 2022-10-20 14:14
@mikhailxyz I'm still getting the same error and I don't see any changes in the package version of `@gnosis.pm/safe-apps-sdk`
